addons:
  apt:
    sources:
      - chef-stable-xenial
    packages:
      - chef-workstation

install: echo "skip bundle install"

branches:
  only:
    - master
    - /^(?i:travis).*$/

services: docker

env:
  matrix:
    - INSTANCE=current-ver-amazonlinux
    - INSTANCE=current-ver-amazonlinux-2
    - INSTANCE=current-ver-debian-9
    - INSTANCE=current-ver-debian-10
    - INSTANCE=current-ver-centos-7
    - INSTANCE=current-ver-centos-8
    - INSTANCE=current-ver-oraclelinux-7
    - INSTANCE=current-ver-oraclelinux-8
    - INSTANCE=current-ver-fedora-latest
    - INSTANCE=current-ver-ubuntu-1804
    - INSTANCE=current-ver-ubuntu-2004
    - INSTANCE=previous-ver-amazonlinux
    - INSTANCE=previous-ver-amazonlinux-2
    - INSTANCE=previous-ver-debian-9
    - INSTANCE=previous-ver-debian-10
    - INSTANCE=previous-ver-centos-7
    - INSTANCE=previous-ver-centos-8
    - INSTANCE=previous-ver-oraclelinux-7
    - INSTANCE=previous-ver-oraclelinux-8
    - INSTANCE=previous-ver-fedora-latest
    - INSTANCE=previous-ver-ubuntu-1804
    - INSTANCE=previous-ver-ubuntu-2004

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version

script: CHEF_LICENSE=accept KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  allow_failures:
    - env: INSTANCE=previous-ver-oraclelinux-7
    - env: INSTANCE=previous-ver-oraclelinux-8
    - env: INSTANCE=current-ver-oraclelinux-7
    - env: INSTANCE=current-ver-oraclelinux-8
    - env: INSTANCE=previous-ver-fedora-latest
    - env: INSTANCE=current-ver-fedora-latest
  include:
    - script:
      - delivery local all
      env:
        - UNIT_AND_LINT=1
        - CHEF_LICENSE=accept
